stages:
  - deploy
deploy_job:
  stage: deploy
  script:
    - |
      rsync -az -e "ssh -i ~/.ssh/runner" --exclude=".git/" --exclude=".gitlab-ci.yml" --delete ./ $webserver:$wwwpath/peternilsson.info
      ssh -i ~/.ssh/runner $webserver "
        rm -f $wwwpath/peternilsson.info/README.md
        rm -f $wwwpath/peternilsson.info/LICENSE
      "